### ISSUE TITLE
PDF info not use by the LLM

### ISSUE THREAD

**Issue by Braindamage010063** [amscotti/local-LLM-with-RAG#7]
Hello, this is an amazing project example for me.
But when i tried to create my own PDF file which introduce myself, i find it hard for the model to recon of what i said and respond base on the document info i gave.

I assume this example can train with additional private files and respond it accordingly? Thanks.

**Comment by amscotti** [comment]
Yes, but it sounds more like a Retrieval-Augmented Generation (RAG) and how vector databases work type of issue. The question that you're asking and how the documents are being scored based on your question may not be retrieving the document where you introduce yourself. As this is just an example project, the RAG implementation is quite arbitrary, whereas you would see many more techniques being used in a real production application. One of these techniques would be re-ranking the documents to ensure relevancy.

You can update the code to send your query directly to ChromaDB so you can see what documents are coming back. I'm guessing the document where you introduce yourself will not be on the list. You can also play with the chunking size and overlap; this may help bring more relevant documents to the top of the list. You can also try different embeddings models.

RAG is a complex topic with many different avenues for fine-tuning, but I'm not shocked to hear that this arbitrary approach is unable to find a document.

**Comment by Victordeleusse** [comment]
That s a question i have when following your code : how the result of  ```docs = db.similarity_search(user_input)``` is used ? And how to give this "context" to my model ?

**Comment by amscotti** [comment]
This is done with this line of code from `app.py`
```python
qa_chain = RetrievalQA.from_chain_type(
    llm,
    retriever=db.as_retriever(search_kwargs={"k": 8}),
    chain_type_kwargs={"prompt": PROMPT},
)
```

RetrievalQA is coming from the LangChain framework and abstracts some of the work of pulling the data from ChromaDB.

You could take this a part, and pull the data from the database separately, and provide this context into the prompt as part of a chain.
