### ISSUE TITLE
Hi, just curious about the responses from various models

### ISSUE THREAD

**Issue by LittleMonster104** [amscotti/local-LLM-with-RAG#8]
Hi, I run an example by asking a question " how to play basketball?" by default setting, I got below:

Please enter your question (or type 'exit' to end): how to play basketball
 The research provided does not contain specific instructions for playing basketball. However, here is a general process or instructions for playing basketball:

1. Form two teams (usually five players each).
2. One team starts with possession of the ball at one end of the court.
3. The objective is to shoot the ball through the hoop of the opponent's basket while preventing them from doing the same.
4. To advance the ball up the court, players pass it to each other by throwing or dribbling it. A player cannot take more than two steps without dribbling the ball first.
5. Players can move without dribbling the ball but must stand still for a moment before passing or shooting.
6. After ten seconds, if no shot is attempted, possession of the ball changes to the opposing team.
7. A foul by a defender results in the offended player receiving two free throws (if the shot attempts are missed, one more free throw is given). If the shot is successful, the score increases by one point and play continues.
8. The game consists of four quarters, each lasting 10 minutes, with a 15-minute halftime break. Overtime periods can be added if the score is tied at the end of regulation time.
9. The team with the most points at the end of the game wins.

But when I changed the model to llama3 or even 70b version, I only only got below response: Can you please explain to me? Thx

Please enter your question (or type 'exit' to end): how to play basketball
I can't answer this question as it is unrelated to the provided research. The research documents appear to be focused on topics such as dialogue generation, prompt engineering, software development, and chatbots, but do not provide information on the rules and techniques of playing basketball.

**Comment by amscotti** [comment]
It all depends on the model's capability of following instructions. Larger models are typically better at following the instructions provided, which is why you're probably getting a more accurate response from Llama 3 models. Llama 3 is a newer model than Mistral.

If you look at [llm.py#L24](https://github.com/amscotti/local-LLM-with-RAG/blob/main/llm.py#L24), you can see that I've instructed the model to reply that it's unable to answer the question if no research is provided or if the research is irrelevant to the question.

Typically in an actual production RAG application, you wouldn't want the LLM to provide any information that does not have research. This is to help prevent hallucinations of the LLM using its built-in knowledge over references. In a production application, you would be focusing on gearing the prompt for a single model. In this application, since you can switch models, I've only done a little optimization for smaller models to ensure that instructions are followed.

**Comment by LittleMonster104** [comment]
Thanks, so you mean you optimize the Mistral yourself， can you pls kindly tell me you how to do it?

Cheers

**Comment by amscotti** [comment]
Sure, by optimize I mean working on improving the prompt with "prompt engineering" techniques.

Generally, there are some ways that you could do this. Sometimes rewriting the instructions for clarity can help, or reiterating the important instructions at the end. If you have enough context window space, you can also provide an example or a couple of examples to help.

In this case, I would try repeating the instruction toward the end of the prompt to reiterate that it should not give any answer that's not based upon valid research, and then test to see if there are improvements for the input.

**Comment by LittleMonster104** [comment]
thanks, I mean how do you make the  Mistral to answer appropriately like my example even there is no know in the Research?

**Comment by amscotti** [comment]
I'm not exactly sure what you're asking. What do you mean by "appropriately"?

If by "appropriately" you mean not providing an answer from the model's knowledge if there is no research, then I would use the techniques from my previous message and update the prompt.

If you want the model to answer, even if there is no research, you would update the prompt to remove the instructions about what to do if there is no research.

In both cases, it involves updating the prompt. I will say that typically in applications using RAG techniques, you're trying to minimize hallucination and have the model only answer questions that it has references for, but of course, your use case may be different. So updating the prompt to match what you want would be needed.

**Comment by LittleMonster104** [comment]
Thanks, I understand your previous message and yes, I should update the prompt to remove the instructions about what to do if there is no research. But as I ask in the first message, why currently if I use the default [mistral) model, I can still get some useful answers even there is no research: Where did you did the optimization? Below is an example:

Please enter your question (or type 'exit' to end): how to play basketball
The research provided does not contain specific instructions for playing basketball. However, here is a general process or instructions for playing basketball:

Form two teams (usually five players each).
One team starts with possession of the ball at one end of the court.
The objective is to shoot the ball through the hoop of the opponent's basket while preventing them from doing the same.
To advance the ball up the court, players pass it to each other by throwing or dribbling it. A player cannot take more than two steps without dribbling the ball first.
Players can move without dribbling the ball but must stand still for a moment before passing or shooting.
After ten seconds, if no shot is attempted, possession of the ball changes to the opposing team.
A foul by a defender results in the offended player receiving two free throws (if the shot attempts are missed, one more free throw is given). If the shot is successful, the score increases by one point and play continues.
The game consists of four quarters, each lasting 10 minutes, with a 15-minute halftime break. Overtime periods can be added if the score is tied at the end of regulation time.
The team with the most points at the end of the game wins.

When I changed the model to llama3 or even 70b version, I only only got below response: Which is work as expected.

Please enter your question (or type 'exit' to end): how to play basketball
I can't answer this question as it is unrelated to the provided research. The research documents appear to be focused on topics such as dialogue generation, prompt engineering, software development, and chatbots, but do not provide information on the rules and techniques of playing basketball.

**Comment by LittleMonster104** [comment]
I got it now. Thx
